### ISSUE TITLE
[question] onBootstrap

### ISSUE THREAD

**Issue by paulogr** [ngx-universal/express-engine#4]
```
    appRef.isStable
      .filter(stable => stable)
      .first()
      .subscribe(() => {
        transferState.inject();
      });
```

Is this garanteed?

I have a medium-size angular application and I'm trying to apply the state transfer but my state is being injected before the backend calls...

Anyone had this problem? What can I doing wrong? 
Thank you!

**Comment by fulls1z3** [comment]
Hi @paulogr, were these backend calls provided using APP_INITIALIZER token?

**Comment by paulogr** [comment]
No, wasn't. How can I use the APP_INITIALIZER token for backend calls?

Sorry, if I don't get the message and thank you for your help.

**Comment by fulls1z3** [comment]
Easy, if you use ngx-config for example the backend calls are sent before everything initializes.

Well, i see that's not the case now. I'll test this on a toy project (in weekend - if got lucky with time) and see what's happening.
